name: Test, Build, and Deploy | Modul 01 - Lab 2.2 Senior Project
# This workflow will test, build, and deploy the project to the server when a push is made to the main branch.
# This workflow will test, build, and deploy the project to the server when a push is made to the main branch.
#   a
on: 
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps: 
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-praktikan4
            PROJECT_DIR="${HOME}/senpro/533842/modul02/modul-01-lab22-github-action"
            REPOSITORY="git@github.com:dnday/modul-01-lab22-github-action.git"

            echo "Cek folder project"
            mkdir -p "${HOME}/senpro/533842/modul02"
            if [ -d "$PROJECT_DIR/.git" ]; then
              echo "Repository sudah ada. Building..."
              cd "$PROJECT_DIR"
              git restore .
              git pull --ff-only origin main
            else
              echo "Repository belum di-clone. Cloning..."
              rm -rf "$PROJECT_DIR"
              git clone "$REPOSITORY" "$PROJECT_DIR"
              cd "$PROJECT_DIR"
            fi

            echo "Install Package dan Build Project"
            rm -rf "$PROJECT_DIR/node_modules" "$PROJECT_DIR/.next" "$PROJECT_DIR/out"
            npm cache clean --force
            npm ci --no-audit --no-fund
            npm run build