name: Test, Build, and Deploy | Modul 01 - Lab 2.2 Senior Project
# This workflow will test, build, and deploy the project to the server when a push is made to the main branch.
# This workflow will test, build, and deploy the project to the server when a push is made to the main branch.
on: 
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps: 
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.SSH/ssh-praktikan4
            echo "Cek folder project";
            [ ! -d "${HOME}/senpro/533842/modul02/senpro-github-action/" ] &&
              {
                echo "Repository belum di-clone. Cloning...";
                mkdir -p ~/senpro/533842/modul02;
                git clone https://github.com/dnday/modul-01-lab22-github-action;
                echo " Install Package dan Build Project";
                npm instal;
                npm run build;
              } ||
              {
                echo "Repository sudah ada. Building...";
                cd ~/senpro/533842/modul02/se3npro-github-action;
                git restore .;
                git pull origin main;
                echo " Install Package dan Build Project";
                npm install;
                npm run build;
              }